---
- name: Add Postgres repo to sources list
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present
  sudo: yes

- name: Add key for Postgres repo
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  sudo: yes

- name: install postgresql packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  tags: [packages]
  with_items:
    - "postgresql-client-{{ postgres_version }}"

- name: install postgresql packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  tags: [packages]
  with_items:
    - "postgresql-{{ postgres_version }}"
    - libpq-dev
    - "postgresql-contrib-{{ postgres_version }}"
    - libxslt-dev
    - libxml2-dev
