---
#  - name: Update apt-get indicies
 #   shell: sudo apt-get update && apt-get upgrade -y

  - name: Install common packages
    shell: curl -sSL {{ SCRIPTS }}/install-common.sh | bash

  - name: Configure Service Manager
    shell: wget {{ MANAGER }}/service-manager.properties

  - name: Get Config File
    shell: wget {{ MANAGER }}/ServiceManager.config

  - name: Get the program used to transform the ServiceManager.config file into the various xml files.
    unarchive:
      src: http://downloads.lappsgrid.org/{{ SMG }}.tgz
      dest: playbook_dir

  - name: Fixing permissions
    shell: chmod +x {{ SMG }}/smg

  - name: Generating XML files....
    shell: smg-1.1.0-SNAPSHOT/smg ServiceManager.config

  - name: Source db.config
    shell: source db.config

  - name: Create postgres User
    shell: sudo -u postgres createuser -S -D -R $ROLENAME

  - name: Set psql user password
    shell: sudo -u postgres psql --command "ALTER USER  $ROLENAME  WITH PASSWORD '$PASSWORD'"

  - name: Create Database
    shell: sudo -u postgres createdb $DATABASE -O $ROLENAME  -E 'UTF8'

  - name: Start Tomcat installation...
    shell: curl -sSL "{{ MANAGER }}"/install-tomcat.sh | bash

  - name: Moving XML Files....
    shell: cp tomcat-users.xml "{{ TOMCAT_MANAGER }}"/conf

  - name: Moving XML Files....
    shell: cp service_manager.xml "{{ TOMCAT_MANAGER }}"/conf/Catalina/localhost

  - name: Moving XML Files....
    shell: cp tomcat-users-bpel.xml "{{ TOMCAT_BPEL }}"/conf/tomcat-users.xml

  - name: Moving XML Files....
    shell: cp active-bpel.xml "{{ TOMCAT_BPEL }}"/conf/Catalina/localhost

  - name: Moving XML Files....
    shell: cp langrid.ae.properties "{{ TOMCAT_BPEL }}"/bpr

  - name: Downloading Service Manager WAR file
    shell: wget https://github.com/openlangrid/langrid/releases/download/servicegrid-core-20161206/jp.go.nict.langrid.webapps.servicegrid-core.jxta-p2p.nict-nlp-20161206.war

  - name: Moving War files
    shell: mv `ls *.war | head -1` $TOMCAT_MANAGER/webapps/service_manager.war

  - name: Toggle Tomcat
    shell: |
      sh files/start_tomcat.sh
      wait_for_start "{{ TOMCAT_MANAGER }}"
      wait_for_start "{{ TOMCAT_BPEL }}"
      sh files/stop_tomcat.sh

  - name: Create Indicies
    shell: |
      wget $MANAGER/create_indices.sql
      cat create_indices.sql | sudo -u postgres psql $DATABASE

  - name: Creating Stored Procedure
    shell: |
      wget $MANAGER/create_storedproc.sql
      cat create_storedproc.sql | sudo -u postgres psql $DATABASE

  - name: Changing owner of the stored procedure.
    shell: |
      echo "ALTER FUNCTION \"AccessStat.increment\"(character varying, character varying, character varying, character varying, character varying, timestamp without time zone, timestamp without time zone, integer, timestamp without time zone, integer, timestamp without time zone, integer, integer, integer, integer) OWNER TO $ROLENAME" > alter.sql
      cat alter.sql | sudo -u postgres psql $DATABASE

  - name: Securing the Tomcat installations
    shell: sh files/secure_directories.sh

  - name: Start Tomcat
    shell: sh files/start_tomcat.sh
